
    create table title_basics (
       tconst varchar(255) not null,
        end_year smallint,
        genres binary(255),
        is_adult boolean,
        primary_title varchar(255),
        runtime_minutes smallint,
        start_year smallint,
        title_type varchar(255),
        primary key (tconst)
    );

    create table name_basics (
       nconst varchar(255) not null,
        birth_year smallint not null,
        death_year smallint,
        primary_name varchar(255) not null,
        primary key (nconst)
    );

    create table name_basics_known_for_titles (
       name_basics_nconst varchar(255) not null,
        known_for_titles_tconst varchar(255) not null
    );

    create table name_basics_primary_profession (
       name_basics_nconst varchar(255) not null,
        primary_profession varchar(255)
    );

    create table title_basics (
       tconst varchar(255) not null,
        end_year smallint,
        is_adult boolean,
        original_title varchar(255) not null,
        primary_title varchar(255) not null,
        runtime_minutes smallint,
        start_year smallint,
        title_type varchar(50) not null,
        primary key (tconst)
    );

    create table title_principal (
       id integer generated by default as identity,
        category varchar(255),
        characters varchar(255),
        job varchar(255),
        nconst varchar(255),
        ordering integer,
        tconst varchar(255) not null,
        primary key (id)
    );

    create table title_basics_genres (
       title_basics_tconst varchar(255) not null,
        genres varchar(255)
    );

    alter table name_basics_known_for_titles 
       add constraint FKdo3kulyivyamqkoa95alc296w 
       foreign key (known_for_titles_tconst) 
       references title_basics;

    alter table name_basics_known_for_titles 
       add constraint FK7vyu3wpy0tg5lsxygyvsl320y 
       foreign key (name_basics_nconst) 
       references name_basics;

    alter table name_basics_primary_profession 
       add constraint FKg31dvvmlm7ij6to96bojecbwn 
       foreign key (name_basics_nconst) 
       references name_basics;

    alter table title_basics_genres 
       add constraint FK19usw0e5vus8jg38uggrvg0tf 
       foreign key (title_basics_tconst) 
       references title_basics;
